import os
import argparse
import yaml
import csv

def make_title(config):

    if "title" in config:
        title = config["title"]
        if "#" not in title:
            title = "## " + title

    else:
        if config["sequencing_centre_text"] == "DEFAULT":
            title = " ## Cluster investigation "
        else:
            title = " ## Cluster investigation for sequences generated by " + seq_centre

    config["title"] = title

def report_date(config):

    if report_date in config:
        date = config["report_date"]
        config["report_date"] = f'This investigation was started on {date}'

    else:
        config["report_date"] = ""

def description(config):

    if "description" in config:
        description = config["description"].rstrip("\n")
        if "#" in description:
            description = description.lstrip("'").rstrip("'")
             
    else:
        description = ""

    if "\\n" in description:
        description_lst = description.split("\\n")
        description_str = ""
        for i in description_lst:
            description_str += f'print("{i}")' + "\n"

        config["description"] = description_str

    else:
        config["description"] = f'print("{description}")'

def authors(config):

    if "authors" in config:

        authors_str = config["authors"]

        config["authors"] = "**Authors**: " + authors_str

    else:
        config["authors"] = ""


def free_text_args(config):
    print("MAKING REPORT ARGS")
    report_date(config)
    description(config)
    authors(config)

