#!/usr/bin/env python

import csv
from Bio import SeqIO
import os


##### Configuration #####

if config.get("force"):
    config["force"] = "--forceall "

if config["quiet_mode"]==True:
    config["quiet_mode"] = "--quiet"
else:
    config["quiet_mode"] = ""

##### Target rules #####
if config.get("launch_browser"):
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"], "civet_report.md"),
            os.path.join(config["outdir"],"local_trees","collapse_report.txt"),
            os.path.join(config["outdir"],"civet_report.html")
else:
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"], "civet_report.md"),
            os.path.join(config["outdir"],"local_trees","collapse_report.txt")

##### Modules #####
include: "assess_input_file.smk"
