#!/usr/bin/env python

import csv
from Bio import SeqIO
import os

output_prefix = config["output_prefix"]
##### Configuration #####

if config.get("force"):
    config["force"] = "--forceall "


##### Target rules #####
rule all:
    input:
        os.path.join(config["outdir"],"combined_metadata.csv"),
        os.path.join(config["outdir"], "report",f"{output_prefix}.md"),
        os.path.join(config["outdir"],"local_trees","collapse_report.txt"),
        os.path.join(config["outdir"],"report",f"{output_prefix}.html")

##### Modules #####
include: "assess_input_file.smk"
