#!/usr/bin/env python

import csv
from Bio import SeqIO
import os

##### Configuration #####

if config.get("force"):
    config["force"] = "--forceall "
else:
    config["force"] = ""


##### Target rules #####

if config["remote"] == "True":
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"],"lineage_trees_remote","lineage_tree_summary.txt")
else:
    rule all:
        input:
            os.path.join(config["outdir"],"combined_metadata.csv"),
            os.path.join(config["outdir"],"lineage_trees","lineage_tree_summary.txt")


##### Modules #####
include: "assess_input_file.smk"
